### ISSUE TITLE
大佬 更新1下呗~

### ISSUE THREAD

**Issue by aimarxjg** [chflame163/ComfyUI_WordCloud#4]
据说这个分词速度是jieba的两倍。
https://github.com/liwenju0/cutword?continueFlag=203a2a4b66ba9142469bdb8c6781ab8a

（那个高级示例工作流，把字体填充到选定图案所需的抠图工具需要CUDA11.8,我是12.3有没有类似能替代的呀节点呀😣）

**Comment by chflame163** [comment]
这个好棒，安排

**Comment by chflame163** [comment]
类似节点有很多啊，rembg, clip seg等等
> （那个高级示例工作流，把字体填充到选定图案所需的抠图工具需要CUDA11.8,我是12.3有没有类似能替代的呀节点呀😣）

**Comment by chflame163** [comment]
> （那个高级示例工作流，把字体填充到选定图案所需的抠图工具需要CUDA11.8,我是12.3有没有类似能替代的呀节点呀😣）
似乎cuda要求没那么严格，我是12.1 可以跑

**Comment by chflame163** [comment]
> > 据说这个分词速度是jieba的两倍。
> > https://github.com/liwenju0/cutword?continueFlag=203a2a4b66ba9142469bdb8c6781ab8a
> > 这个好棒，安排

我试了，还有bug，等稳定版吧
