### ISSUE TITLE
add mask output not appearing even when updated?

### ISSUE THREAD

**Issue by plaidam** [chflame163/ComfyUI_WordCloud#5]
<img width="547" alt="Screenshot 2024-01-24 at 7 27 10 PM" src="https://github.com/chflame163/ComfyUI_WordCloud/assets/6028016/8d19c0ea-879b-4a79-b9c5-1704f3df584a">

I love this Node and want to use the updated features, especially the Update add mask output. I've updated the Node and then deleted and installed it from scratch, and it doesn't appear when doing either. Any idea why?

**Comment by chflame163** [comment]
I cannot reproduce your question, so I cannot make any judgment. However, I would remind you that if an old version of the node is used in the workflow, please delete it and add the node again.
