### ISSUE TITLE
Node Graph Visualisation

### ISSUE THREAD

**Issue by rafstahelin** [chflame163/ComfyUI_WordCloud#7]
Could you create another node but to visualise node graph from a caption folder, to see tag frequency? 

![image](https://github.com/chflame163/ComfyUI_WordCloud/assets/64715158/75d38992-f25c-4ffc-8ec8-d4794d296afa)

Would be so useful for training

**Comment by chflame163** [comment]
That a lot has been going on lately. If had time, I'd think about it.

**Comment by rafstahelin** [comment]
No worries, thanks for word cloud pretty awesome for trainers Best, Raf On 21 Apr 2024, at 13:24, chflame163 ***@***.***> wrote:﻿
That a lot has been going on lately. If had time, I'd think about it.

**Comment by rafstahelin** [comment]
> That a lot has been going on lately. If had time, I'd think about it. 

That's too bad
